#include <inttypes.h>

enum class LangId : uint16_t {
    ar_SA = 1025,       // Arabic - Saudi Arabia
    bg_BG = 1026,       // Bulgarian
    ca_ES = 1027,       // Catalan
    zh_TW = 1028,       // Chinese - Taiwan
    cs_CZ = 1029,       // Czech
    da_DK = 1030,       // Danish
    de_DE = 1031,       // German - Germany
    el_GR = 1032,       // Greek
    en_US = 1033,       // English - United States
    es_ES_trad = 1034,  // Spanish - Spain (Traditional)
    fi_FI = 1035,       // Finnish
    fr_FR = 1036,       // French - France
    he_IL = 1037,       // Hebrew
    hu_HU = 1038,       // Hungarian
    is_IS = 1039,       // Icelandic
    it_IT = 1040,       // Italian - Italy
    ja_JP = 1041,       // Japanese
    ko_KR = 1042,       // Korean
    nl_NL = 1043,       // Dutch - Netherlands
    nb_NO = 1044,       // Norwegian (Bokmål)
    pl_PL = 1045,       // Polish
    pt_BR = 1046,       // Portuguese - Brazil
    rm_CH = 1047,       // Rhaeto-Romanic
    ro_RO = 1048,       // Romanian
    ru_RU = 1049,       // Russian
    hr_HR = 1050,       // Croatian
    sk_SK = 1051,       // Slovak
    sq_AL = 1052,       // Albanian - Albania
    sv_SE = 1053,       // Swedish
    th_TH = 1054,       // Thai
    tr_TR = 1055,       // Turkish
    ur_PK = 1056,       // Urdu - Pakistan
    id_ID = 1057,       // Indonesian
    uk_UA = 1058,       // Ukrainian
    be_BY = 1059,       // Belarusian
    sl_SI = 1060,       // Slovenian
    et_EE = 1061,       // Estonian
    lv_LV = 1062,       // Latvian
    lt_LT = 1063,       // Lithuanian
    tg_Cyrl_TJ = 1064,  // Tajik
    fa_IR = 1065,       // Persian
    vi_VN = 1066,       // Vietnamese
    hy_AM = 1067,       // Armenian - Armenia
    az_Latn_AZ = 1068,  // Azeri (Latin)
    eu_ES = 1069,       // Basque
    wen_DE = 1070,      // Sorbian
    mk_MK = 1071,       // F.Y.R.O. Macedonian
    st_ZA = 1072,       // Sutu
    ts_ZA = 1073,       // Tsonga
    tn_ZA = 1074,       // Tswana
    ven_ZA = 1075,      // Venda
    xh_ZA = 1076,       // Xhosa
    zu_ZA = 1077,       // Zulu
    af_ZA = 1078,       // Afrikaans - South Africa
    ka_GE = 1079,       // Georgian
    fo_FO = 1080,       // Faroese
    hi_IN = 1081,       // Hindi
    mt_MT = 1082,       // Maltese
    se_NO = 1083,       // Sami
    gd_GB = 1084,       // Gaelic (Scotland)
    yi = 1085,          // Yiddish
    ms_MY = 1086,       // Malay - Malaysia
    kk_KZ = 1087,       // Kazakh
    ky_KG = 1088,       // Kyrgyz (Cyrillic)
    sw_KE = 1089,       // Swahili
    tk_TM = 1090,       // Turkmen
    uz_Latn_UZ = 1091,  // Uzbek (Latin)
    tt_RU = 1092,       // Tatar
    bn_IN = 1093,       // Bengali (India)
    pa_IN = 1094,       // Punjabi
    gu_IN = 1095,       // Gujarati
    or_IN = 1096,       // Oriya
    ta_IN = 1097,       // Tamil
    te_IN = 1098,       // Telugu
    kn_IN = 1099,       // Kannada
    ml_IN = 1100,       // Malayalam
    as_IN = 1101,       // Assamese
    mr_IN = 1102,       // Marathi
    sa_IN = 1103,       // Sanskrit
    mn_MN = 1104,       // Mongolian (Cyrillic)
    bo_CN = 1105,       // Tibetan - China
    cy_GB = 1106,       // Welsh
    km_KH = 1107,       // Khmer
    lo_LA = 1108,       // Lao
    my_MM = 1109,       // Burmese
    gl_ES = 1110,       // Galician
    kok_IN = 1111,      // Konkani
    mni = 1112,         // Manipuri
    sd_IN = 1113,       // Sindhi - India
    syr_SY = 1114,      // Syriac
    si_LK = 1115,       // Sinhalese - Sri Lanka
    chr_US = 1116,      // Cherokee - United States
    iu_Cans_CA = 1117,  // Inuktitut
    am_ET = 1118,       // Amharic - Ethiopia
    tmz = 1119,         // Tamazight (Arabic)
    ks_Arab_IN = 1120,  // Kashmiri (Arabic)
    ne_NP = 1121,       // Nepali
    fy_NL = 1122,       // Frisian - Netherlands
    ps_AF = 1123,       // Pashto
    fil_PH = 1124,      // Filipino
    dv_MV = 1125,       // Divehi
    bin_NG = 1126,      // Edo
    fuv_NG = 1127,      // Fulfulde - Nigeria
    ha_Latn_NG = 1128,  // Hausa - Nigeria
    ibb_NG = 1129,      // Ibibio - Nigeria
    yo_NG = 1130,       // Yoruba
    quz_BO = 1131,      // Quecha - Bolivia
    nso_ZA = 1132,      // Sepedi
    ig_NG = 1136,       // Igbo - Nigeria
    kr_NG = 1137,       // Kanuri - Nigeria
    gaz_ET = 1138,      // Oromo
    ti_ER = 1139,       // Tigrigna - Ethiopia
    gn_PY = 1140,       // Guarani - Paraguay
    haw_US = 1141,      // Hawaiian - United States
    la = 1142,          // Latin
    so_SO = 1143,       // Somali
    ii_CN = 1144,       // Yi
    pap_AN = 1145,      // Papiamentu
    ug_Arab_CN = 1152,  // Uighur - China
    mi_NZ = 1153,       // Maori - New Zealand
    ar_IQ = 2049,       // Arabic - Iraq
    zh_CN = 2052,       // Chinese - China
    de_CH = 2055,       // German - Switzerland
    en_GB = 2057,       // English - United Kingdom
    es_MX = 2058,       // Spanish - Mexico
    fr_BE = 2060,       // French - Belgium
    it_CH = 2064,       // Italian - Switzerland
    nl_BE = 2067,       // Dutch - Belgium
    nn_NO = 2068,       // Norwegian (Nynorsk)
    pt_PT = 2070,       // Portuguese - Portugal
    ro_MD = 2072,       // Romanian - Moldava
    ru_MD = 2073,       // Russian - Moldava
    sr_Latn_CS = 2074,  // Serbian (Latin)
    sv_FI = 2077,       // Swedish - Finland
    ur_IN = 2080,       // Urdu - India
    az_Cyrl_AZ = 2092,  // Azeri (Cyrillic)
    ga_IE = 2108,       // Gaelic (Ireland)
    ms_BN = 2110,       // Malay - Brunei Darussalam
    uz_Cyrl_UZ = 2115,  // Uzbek (Cyrillic)
    bn_BD = 2117,       // Bengali (Bangladesh)
    pa_PK = 2118,       // Punjabi (Pakistan)
    mn_Mong_CN = 2128,  // Mongolian (Mongolian)
    bo_BT = 2129,       // Tibetan - Bhutan
    sd_PK = 2137,       // Sindhi - Pakistan
    tzm_Latn_DZ = 2143, // Tamazight (Latin)
    ks_Deva_IN = 2144,  // Kashmiri (Devanagari)
    ne_IN = 2145,       // Nepali - India
    quz_EC = 2155,      // Quecha - Ecuador
    ti_ET = 2163,       // Tigrigna - Eritrea
    ar_EG = 3073,       // Arabic - Egypt
    zh_HK = 3076,       // Chinese - Hong Kong SAR
    de_AT = 3079,       // German - Austria
    en_AU = 3081,       // English - Australia
    es_ES_mod = 3082,   // Spanish - Spain (Modern)
    fr_CA = 3084,       // French - Canada
    sr_Cyrl_CS = 3098,  // Serbian (Cyrillic)
    quz_PE = 3179,      // Quecha - Peru
    ar_LY = 4097,       // Arabic - Libya
    zh_SG = 4100,       // Chinese - Singapore
    de_LU = 4103,       // German - Luxembourg
    en_CA = 4105,       // English - Canada
    es_GT = 4106,       // Spanish - Guatemala
    fr_CH = 4108,       // French - Switzerland
    hr_BA = 4122,       // Croatian (Bosnia/Herzegovina)
    ar_DZ = 5121,       // Arabic - Algeria
    zh_MO = 5124,       // Chinese - Macao SAR
    de_LI = 5127,       // German - Liechtenstein
    en_NZ = 5129,       // English - New Zealand
    es_CR = 5130,       // Spanish - Costa Rica
    fr_LU = 5132,       // French - Luxembourg
    bs_Latn_BA = 5146,  // Bosnian (Bosnia/Herzegovina)
    ar_MO = 6145,       // Arabic - Morocco
    en_IE = 6153,       // English - Ireland
    es_PA = 6154,       // Spanish - Panama
    fr_MC = 6156,       // French - Monaco
    ar_TN = 7169,       // Arabic - Tunisia
    en_ZA = 7177,       // English - South Africa
    es_DO = 7178,       // Spanish - Dominican Republic
    fr_029 = 7180,      // French - West Indies
    ar_OM = 8193,       // Arabic - Oman
    en_JM = 8201,       // English - Jamaica
    es_VE = 8202,       // Spanish - Venezuela
    fr_RE = 8204,       // French - Reunion
    ar_YE = 9217,       // Arabic - Yemen
    en_029 = 9225,      // English - Caribbean
    es_CO = 9226,       // Spanish - Colombia
    fr_CG = 9228,       // French - Democratic Rep. of Congo
    ar_SY = 10241,      // Arabic - Syria
    en_BZ = 10249,      // English - Belize
    es_PE = 10250,      // Spanish - Peru
    fr_SN = 10252,      // French - Senegal
    ar_JO = 11265,      // Arabic - Jordan
    en_TT = 11273,      // English - Trinidad
    es_AR = 11274,      // Spanish - Argentina
    fr_CM = 11276,      // French - Cameroon
    ar_LB = 12289,      // Arabic - Lebanon
    en_ZW = 12297,      // English - Zimbabwe
    es_EC = 12298,      // Spanish - Ecuador
    fr_CI = 12300,      // French - Cote d'Ivoire
    ar_KW = 13313,      // Arabic - Kuwait
    en_PH = 13321,      // English - Philippines
    es_CL = 13322,      // Spanish - Chile
    fr_ML = 13324,      // French - Mali
    ar_AE = 14337,      // Arabic - U.A.E.
    en_ID = 14345,      // English - Indonesia
    es_UY = 14346,      // Spanish - Uruguay
    fr_MA = 14348,      // French - Morocco
    ar_BH = 15361,      // Arabic - Bahrain
    en_HK = 15369,      // English - Hong Kong SAR
    es_PY = 15370,      // Spanish - Paraguay
    fr_HT = 15372,      // French - Haiti
    ar_QA = 16385,      // Arabic - Qatar
    en_IN = 16393,      // English - India
    es_BO = 16394,      // Spanish - Bolivia
    en_MY = 17417,      // English - Malaysia
    es_SV = 17418,      // Spanish - El Salvador
    en_SG = 18441,      // English - Singapore
    es_HN = 18442,      // Spanish - Honduras
    es_NI = 19466,      // Spanish - Nicaragua
    es_PR = 20490,      // Spanish - Puerto Rico
    es_US = 21514,      // Spanish - United States
    es_419 = 58378,     // Spanish - Latin America
    fr_015 = 58380      // French - North Africa
};